name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - shell: pwsh
        env:
          GITHUB_READ_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd src/FsStore; ./test.ps1

      - shell: pwsh
        env:
          GITHUB_READ_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd src/FsStore; ./pack.ps1

      - run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.actor }}/index.json --name github
      - run: dotnet nuget push src/FsStore/bin/Release/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
